# --- Stage 1: Build ---
FROM node:22-alpine AS builder

# Enable pnpm
RUN corepack enable

WORKDIR /app


# Copy package.json & lockfile
COPY package.json pnpm-lock.yaml ./

# Cài full dependencies (bao gồm dev để build TS)
RUN pnpm install --frozen-lockfile

# Copy Prisma schema trước để generate client
COPY prisma ./prisma

# Generate Prisma client
RUN pnpm exec prisma generate

# Copy toàn bộ source code
COPY . .

# Build NestJS
RUN pnpm run build

# Compile seed.ts sang JS
RUN pnpm exec tsc --project tsconfig.seed.json



# --- Stage 2: Run ---
FROM node:22-alpine

WORKDIR /app
RUN corepack enable

# Copy node_modules prod từ builder
COPY --from=builder /app/node_modules ./node_modules

# Copy Prisma folder (schema + dist seed.js)
COPY --from=builder /app/prisma ./prisma

# Copy NestJS dist
COPY --from=builder /app/dist ./dist

# Copy package.json để prisma seed đọc script
COPY --from=builder /app/package.json ./package.json

# Nếu dùng env file, uncomment:
# COPY --from=builder /app/.env ./.env

# Expose cổng
EXPOSE 3001

# CMD production: migrate -> seed -> start NestJS
CMD ["sh", "-c", "pnpm exec prisma migrate deploy && pnpm exec prisma db seed && node dist/main.js"]
