export const menuItems = [
  // --- Coffee ---
  {
    id: "1",
    category: "coffee",
    name: "Double Espresso",
    price: 59.99,
    size: ["S", "M", "L"],
    calories: 5,
    image: "/image/products/espresso1.png",
    images: [
      "/image/products/espresso1.png",
      "/image/products/espresso2.png",
      "/image/products/espresso3.png"
    ],
    description: "Rich, powerful for the day.",
  },
  {
    id: "2",
    category: "coffee",
    name: "Caramel Frappe",
    price: 49.99,
    size: ["M", "L"],
    calories: 210,
    image: "/image/image2.png",
    description: "Sweet, cool, addictive.",
  },
  {
    id: "3",
    category: "coffee",
    name: "Iced Coffee",
    price: 39.99,
    size: ["S", "M", "L"],
    calories: 90,
    image: "/image/image3.png",
    description: "Fresh, suitable for summer.",
  },
  {
    id: "4",
    category: "coffee",
    name: "Regular Coffee",
    price: 29.99,
    size: ["S", "M"],
    calories: 50,
    image: "/image/image4.png",
    description: "Traditional coffee for everyone.",
  },

  // --- Tea ---
  {
    id: "5",
    category: "tea",
    name: "Matcha Latte",
    price: 45.99,
    size: ["M", "L"],
    calories: 160,
    image: "/image/image1.png",
    description: "Refreshing Japanese green tea, add rich milk.",
  },
  {
    id: "6",
    category: "tea",
    name: "Peach Iced Tea",
    price: 35.99,
    size: ["S", "M", "L"],
    calories: 120,
    image: "/image/image2.png",
    description: "Cool peach tea, cooling off on summer days.",
  },

  // --- Bakery ---
  {
    id: "7",
    category: "bakery",
    name: "Croissant",
    price: 25.99,
    size: ["1 pc"],
    calories: 230,
    image: "/image/image3.png",
    description: "Crispy, fragrant butter croissants.",
  },
  {
    id: "8",
    category: "bakery",
    name: "Cheesecake",
    price: 55.99,
    size: ["1 pc"],
    calories: 350,
    image: "/image/image4.png",
    description: "Rich, sweet cheesecake.",
  },

  // --- Others ---
  {
    id: "9",
    category: "others",
    name: "Orange Juice",
    price: 29.99,
    size: ["S", "M", "L"],
    calories: 110,
    image: "/image/image1.png",
    description: "Freshly squeezed orange juice.",
  },
  {
    id: "10",
    category: "others",
    name: "Mineral Water",
    price: 15.99,
    size: ["500ml"],
    calories: 0,
    image: "/image/image2.png",
    description: "Pure mineral water, natural refreshment.",
  },
];
